### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by chengts95** [rwl/PYPOWER#39]
It seems that there is a tiny mistake with the current master branch in  [ext2int.py Line 151](https://github.com/rwl/PYPOWER/blob/master/pypower/ext2int.py#L151)
where `o["bus"]["e2i"] = zeros(max(o["bus"]["i2e"]) + 1)` should be `o["bus"]["e2i"] = zeros(max(o["bus"]["i2e"]).astype(int) + 1)`, or you will get a` TypeError: 'numpy.float64' object cannot be interpreted as an integer` when you call ext2int().

**Comment by activeshadow** [comment]
I'm seeing this same issue... though the traceback I'm seeing is reporting the line as 152. Makes me sad panda. :cry:

**Comment by activeshadow** [comment]
I'll create a pull request once I can test my fix referenced above.

**Comment by chengts95** [comment]
Although the bug is easy to fix, it is really weird to see the line as 152 instead of 151 in traceback.

**Comment by activeshadow** [comment]
Yeah, I agree. However, the line of code printed in the traceback is the same line of code that's at line 151 in the source, so who knows where the extra line break got added in. That did fix the error I was getting though.
