### ISSUE TITLE
big god，help me!

### ISSUE THREAD

**Issue by Gallenger** [rwl/PYPOWER#52]
how to ' import pypower' to the script,i want to write the code,

**Comment by priyald17** [comment]
`import pypower.api as pp`

**Comment by Gallenger** [comment]
running the 'case9' example and how to extract the 'Bus' matrix or another matrixs from the run results,just like the Matlab,      Thanks for your help

**Comment by priyald17** [comment]
`
ppc = pp.case9()
ppc.keys()  # shows you available keys to extract
`

**Comment by Gallenger** [comment]
oh,thank you so much. i begin to  learn the deep learning in distribution network, maybe a little hard
