### ISSUE TITLE
New pyrlu versions broke some of my PYPOWER applications

### ISSUE THREAD

**Issue by eshoubak** [rwl/PYPOWER#86]
What worked as a solution temporarily was building with 

pip install pyrlu==0.1.2

Well, today while trying to build a new docker image I found that version removed from the pip repositories. 

Anyone else encountered this ? 

I will recreate the error messages with the latest pyrlu and share it here.

**Comment by rwl** [comment]
What version of Python are you using? I think the issue might be that v0.1.2 only has builds for Python <= v3.11.

I am working on replacing PyRLU with a KLU extension due to some performance issues. Hopefully, that will resolve matters.

**Comment by eshoubak** [comment]
My version of Python was 3.10

My Dockerfile compiled again. The machine I had the failure on was a macbook M2, ok things make sense now, probably version 0.1.2 of pyrlu does not have an ARM binary ?

**Comment by rwl** [comment]
Builds for the `aarch64` target architecture were only added in version 0.2.1 of PyRLU:

https://github.com/rwl/pyrlu/issues/1

**Comment by liushaohuai5** [comment]
I think this could be perfectly solved by replacing pyrlu with scipy.sparse.linalg.spsolve
```python
from scipy.sparse.linalg import spsolve

def pplinsolve(A, b):
    """Solves the linear system of equations C{A * x = b}.
    """
    x = spsolve(A, b)
    return x
```

**Comment by rwl** [comment]
I have made `pyrlu` optional and reverted to using `spsolve` while I make some improvements to RLU. By default `spsolve` uses SuperLU which does offer great performance for these types of problem. One possibility is for users to enable UMFPACK by installing `scikits.umfpack`:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.use_solver.html
